language: java
jdk:
- oraclejdk8

script: "mvn deploy --settings settings.xml"
branches:
  except:
  - travis
env:
  global:
  - secure: "XjS5KUwhWudytePEI9MT1tJasbmmaJcP+RWKTnEucM5uws6ogMWZb7flKZvn8EFvgGMXiGV85QmPqPEHA7ktuWRzhRdaWcMgkXC1mmb+k3CHZpUYtibWztQRj/XuRNWpjcGrZ8/I/6VklxNPesqc/7Sw4KOvmd2c4LgkO7yJCVH7hRk7DqzK01Q1icFAvjh9ttXQloS5iEMOWr8GGiJtg6W/gKUzTLfBeakudbs4phxcXmQpLvvXbxnHk0gnVxffogLn+I8T1/X/9S2mr3iQS+sX5mK0pIGQNBmAb9a8qYGZyQdlwGIH9Lrzjjv08IwFxG6UNwMgRTGVCpO1X46G6fVrkAwzPQ0YjsMCwJpBAXzzmN+jeq4l/1wwPssgSbYkpHFRJgIpvUmwTyKVBs7ajjztAQD9i9RkjcKhnfQlB0ewQKFFydgDXD79IVUbw4jkhBDeaehUpUyja8lCOBAifJUllPufnQI2+CMdZs6EmUoPoTUdoZTrc8nn96i0lOFzoIZuj54DwCoXACk0Npz/9dzpusCu55FknmpsutpClWGVZ9Ff/HVgfJp0Cp2FnaLU/Vq4Kn7amMeVCL+WUbByDDIoAE6XYpJrTnMVh4Flcgv+FkUQXC6a9rOfO5KN+nU5zLvrtmo+wQU1wPU8Uz+oAIf4G1CCIjP6/ojWkTGzTwY="
  - secure: "roM37GZ6nRkqFr648PnyExdWqh/KvXeTmReMyCRr9gcviKZ7kPotz+v8ANwLAQA9osK4rbpTEbRjBan2r3I50eNPJqD+jWa98pFnIhX5KJ1ApuGDp+nVGoEJfn2z12AQUZQBupHVsvKohvxW/9G8AWet2ZPYHapL0iYET8lAHOXajkRPyo2Z0MLRZzKHasmuyxY8B9CY7PxSKCYnszYGZhGo74NIdnzuNGrdBfS9y0n29SXmUWm/WVyBNhPfpnvpUk0AJGU8hyCAsaG7w3NVQQwnrj90+ZuZ2EdA3p8SIZZq1Q8HiR/qvUxw7i4EpAy6W7VA/LFeKmSZFyY7MsRMODUtRK7ye/mxO6mVawbVvCZP5E80Nv4N0pNNecymVSVEaIJzqtB9T3+bqeVh9QOcDNTocdOSZ4cviNbgYTIJrBBdQLEQUGk5RAq+7+6Y1g8ei4Tt5w2rvuYqrAHOAH3Hwwi0P7Jx4q/G2+fZQxxConBVvZO8RIPUxT2x65b0BBQJDc7ZFAXyvffzjnv3Khm02qYt+5NHe8Y9J0457PWoTVNxSwvsXuekX9RoGZInyXJaVCoCyzZOeeRMfPCVpDhg4XPRilyWv3XaIOSyCV/OlwmzGg10J81lj+BXzSLCrR2KiGrqgOrC55dnI/hkcWK3iUI9aPWpQB+5eENgVunxBo0="
